name: Dependency scan

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependencies:
    name: Dependency scan
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency scan
        uses: aquasecurity/trivy-action@v0.24.0
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true

